# Generated by Django 3.2.15 on 2022-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='max_players',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
