# Generated by Django 3.2.15 on 2022-08-09 22:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game_sessions', '0002_auto_20220809_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('players', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='max_players',
            field=models.IntegerField(default=0, help_text='Value of 0 allows an infinite number of players', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(to='game_sessions.Player'),
        ),
    ]
