# Generated by Django 3.2.15 on 2022-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_auto_20220809_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='game_sessions.Player'),
        ),
    ]
