# Generated by Django 3.2.15 on 2022-08-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0004_alter_session_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(null=True, to='game_sessions.Player'),
        ),
    ]
